cache:
  directories:
    - $HOME/.composer/cache

stages:
  - code-analysis
  - test

language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - TESTBENCH_VERSION=^4.0
  - TESTBENCH_VERSION=^5.0
  - TESTBENCH_VERSION=^6.0

install:
  - composer require --no-interaction orchestra/testbench:$TESTBENCH_VERSION

before_script:
  - phpenv config-rm xdebug.ini

script: make test

jobs:
  exclude:
    - php: 7.2
      env: TESTBENCH_VERSION=^6.0
  include:
    - stage: code-analysis
      name: Code Style Check
      php: 7.4
      env: TESTBENCH_VERSION=^6.0
      script: make style-check
    - stage: code-analysis
      name: Static Code Analysis
      php: 7.4
      env: TESTBENCH_VERSION=^6.0
      script: make static-analysis
